### ISSUE TITLE
train/val/test_landmarks_3D.csv of CelebA-HQ 

### ISSUE THREAD

**Issue by kennyvoo** [unibas-gravis/Occlusion-Robust-MoFA#1]
Can you  release the train/val/test_landmarks_3D.csv of CelebA-HQ ?

**Comment by kennyvoo** [comment]
I've tried to prepare the landmarks_3d.csv for CelebA-HQ using the 2D-and-3D-face-alignment repo. 
1. So do I produce a 3d landmark or 2d landmark? In the load_dataset.py line  83, the landmark is reshaped into tensors of shape   So, it's a 2d landmarks instead of 3d?
 -  landmark = torch.Tensor(landmark_cpu).reshape(-1,2).transpose(0,1)

**Comment by jo-dean** [comment]
So did you konw it's 3d landmark or 2d landmark?
thank you?

**Comment by ChunLLee** [comment]
2D landmarks are used in our implementation.
