### ISSUE TITLE
Ground truth segmentation masks necessity? RuntimeError and some questions

### ISSUE THREAD

**Issue by adevra** [unibas-gravis/Occlusion-Robust-MoFA#12]
Hello, 
This is the error I'm getting when running Step1
```
(FOCUS) adev@adev-System-Product-Name:~/Desktop/Occlusion-Robust-MoFA$ python Step1_Pretrain_MoFA.py --img_path ./image_root/Dataset
/home/adev/Desktop/Occlusion-Robust-MoFA/models/networks.py
Dataset:./image_root/Dataset/../train_landmarks.csv
Dataset:./image_root/Dataset/../val_landmarks.csv
loading pretrained net_recog r50 from models/ms1mv3_arcface_r50_fp16/backbone.pth
Training ...

Traceback (most recent call last):
  File "Step1_Pretrain_MoFA.py", line 234, in <module>
    test_fg_masks += [fg_mask.reshape(batch,1,224,224)]
RuntimeError: shape '[12, 1, 224, 224]' is invalid for input of size 401408

```

Not sure but maybe this is why I'm getting the error?
**Is it necessary to create GT masks to even run the Step1_Pretrain_MoFA.py ?** if so how can I create those segmentation masks? I'dont have these currently.
_To evaluate the accuracy of the estimated masks, ground truth occlusion segmentation masks are required. Please name the target image as 'image_name.jpg' and ground truth masks as 'image_name_visible_skin_mask.png'._ 

/image_root directory example shows this
```
 ├── train_landmarks.csv      # .csv file for the train set.
 ├── test_landmarks.csv       # .csv file for the test set.
 ├── val_landmarks.csv        # .csv file for the validation set.
 └── all_landmarks.csv        # .csv file for the whole dataset. (optional)
```
Example shows 4 different 68pts landmarks formatted as .csv files but I was able to generate only a single .csv file consisting of 8 images thanks to https://github.com/unibas-gravis/Occlusion-Robust-MoFA/issues/8#issuecomment-1172892319
Do I have to duplicate that one csv file and rename accordingly or is it a totally different process that I didn't understand?

Any feedback would be much appreciated, I really want to get some result (:
Thanks

**Comment by ChunLLee** [comment]
Hi I fixed this, more details please check: 

https://github.com/unibas-gravis/Occlusion-Robust-MoFA/commit/880e3fb71625479b271d9159a14b46b0c78e7ae8

and since the code is fixed, I will close this issue.

It seems that the error you reported is triggered because the dim of the mask estimated using the occlusion-robust loss is not (batch_size x 1 x 224 x 224). You could check if the size of your batch is 12 or not, or if the dimension of the mask is changed somewhere in the code or not.
