### ISSUE TITLE
demo.py problem

### ISSUE THREAD

**Issue by NewtOliver** [unibas-gravis/Occlusion-Robust-MoFA#15]
Hello, I have the following two questions about the operation of demo.py:
1. What should I fill in "--test_mode"?
2. The obj file I get is colorless, so I think this has something to do with "--test_mode"?

**Comment by ChunLLee** [comment]
Hi the argument --test_mode is just a name for your pipeline to tell that you are generating data for a different model/dataset etc. It is not related to the color of the obj file.

If you need to get meshes with texture, check the funchtion  ['write_obj_with_colors'](https://github.com/unibas-gravis/Occlusion-Robust-MoFA/blob/880e3fb71625479b271d9159a14b46b0c78e7ae8/Demo.py#L214). It can be reached by adding the vertex color as an argument to this function.

**Comment by yumkim381** [comment]
Could you please specify more on how to get meshes with texture?

**Comment by yumkim381** [comment]
1. in line 179 of FOCUS_basic.py, change the line to 

```python
self.reconstructed_results.update( {'nonexp_intact_verts':nonexp_vertex_intact,
                'lm_NoW':lmring. 'color':color                     
})
```

2. in line 127, [[Demo.py](http://demo.py/)](http://Demo.py)  add this line 

```python
color = reconstructed_results['color']
```

3. Line 159 [Demo.py](http://demo.py/): add

```python
processed_color = color[iter_save].detach().to('cpu').numpy()
```

4.  Then line 163 modify util.write_obj_with_colors call with 

```python
util.write_obj_with_colors(filepath_woext_path+'.obj', vertexes_temp.T, FOCUSModel.triangles_intact, processed_color.T)
```

And modify the write_obj_with_colors function in line 66 at util.py as s = 'v {} {} {} {} {} {}\n'.format(vertices[i, 0], vertices[i, 1], vertices[i, 2], colors[i, 0], colors[i, 1], colors[i, 2]) if colors is not None else 'v {} {} {}\n'.format(vertices[i, 0], vertices[i, 1], vertices[i, 2])
