### ISSUE TITLE
About the load_object

### ISSUE THREAD

**Issue by jo-dean** [unibas-gravis/Occlusion-Robust-MoFA#2]
Hello,you used the crop_center() function in the code.
I want to ask where the formula `# (x/z/100)^2+((y)/z/0.75)^2 <=1` come from?
And where i can found some material about the crop_center.
Thank you!

**Comment by ChunLLee** [comment]
Hi this function is the approximation to the contours of the expected face region and works to crop the face model. It might be updated in the next version. Thank you for your attention.
