### ISSUE TITLE
About UV maps

### ISSUE THREAD

**Issue by GAPLX** [unibas-gravis/Occlusion-Robust-MoFA#22]
Regarding the results of testing myself on Docker, only OBJ and visualization images were generated. How can I obtain UV maps？

**Comment by ChunLLee** [comment]
Hi, thank you for your interest, but this is out of the scope of this project.
We recommend the following work for you for more information.
[face3d](https://github.com/yfeng95/face3d/blob/master/examples/7_generate_uv_map.py)
