### ISSUE TITLE
Problem in first train step

### ISSUE THREAD

**Issue by NewtOliver** [unibas-gravis/Occlusion-Robust-MoFA#23]
How should I solve this problem? My cuda version is 11.3, python version is 3.8  
![image](https://github.com/unibas-gravis/Occlusion-Robust-MoFA/assets/45253712/36e5622d-db39-4cbf-8d3a-5fd9c810f624)

**Comment by yug125lk** [comment]
change this line in _networks.py_ : `feature = self.net(image, is_shallow)`
to this:
`feature = self.net(image)`
