### ISSUE TITLE
 How to generate the output image with frontal face?

### ISSUE THREAD

**Issue by yug125lk** [unibas-gravis/Occlusion-Robust-MoFA#24]
Hi, thank you so much for sharing this great work, my question is: How to generate the output image with frontal faces? I can't find the angles and translation parameters in the code.
 I found this response in "Deep3DFaceRecon_pytorch"

> Hi, to generate obj file with frontal face, you need to change the predicted pose parameters to zeros.
You can modify the angles and translation here:

[Deep3DFaceRecon_pytorch/models/bfm.py](https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/73d491102af6731bded9ae6b3cc7466c3b2e9e48/models/bfm.py#L263)

Line 263 in [73d4911](https://github.com/sicxu/Deep3DFaceRecon_pytorch/commit/73d491102af6731bded9ae6b3cc7466c3b2e9e48)

 angles = coeffs[:, 224: 227]

**Comment by ChunLLee** [comment]
Hi, in the scripts please change the value of
`camera_param[:,:3]`
to change the rotation angles of the face to get frontal or different poses.
