### ISSUE TITLE
Unable to download publicly available masks on AR datasets

### ISSUE THREAD

**Issue by Jack171516** [unibas-gravis/Occlusion-Robust-MoFA#25]
Hi, thank you very much for this great work, I am having a problem downloading the 120 manually segmented masks provided as GT masks on the AR dataset by the article "Occlusion-Aware 3D Morphable Models and an Illumination Prior for Face Image Analysis". I'm having a problem downloading the 120 manually segmented masks provided as GT masks on the AR dataset by the article "Occlusion-Aware 3D Morphable Models and an Illumination Prior for Face Image Analysis" and I found that I can't download them via the URL given anymore, can you share this resource? Thank you again.

**Comment by ChunLLee** [comment]
Hi, please contact the authors of this work to apply for the data. Since we do not have the right to distribute the dataset we cannot directly send you.
