### ISSUE TITLE
Can you share the model weight and test code?

### ISSUE THREAD

**Issue by Bornblack** [unibas-gravis/Occlusion-Robust-MoFA#3]
Thanks for your great work !
It seems take a good chunk of time to implement the method from scratch.
Can you share the training model weight and test code for the fast testing purpose?

**Comment by LyazS** [comment]
hope for pretrain model again

**Comment by lhyfst** [comment]
need the pretrain model too

**Comment by The-FleetingLove** [comment]
I also really need the pretrain model，Thanks！

**Comment by hyungraelee** [comment]
Thank you for showing amazing results!
I hope to test it with my data.
I also want to get the learned weights. Thanks!

**Comment by ChunLLee** [comment]
Hi the pretrained models are now made public in our docker version. Check the following links to see how to use it:

https://github.com/unibas-gravis/Occlusion-Robust-MoFA/blob/main/README.md#docker-image

https://hub.docker.com/repository/docker/chunluli/focus/tags?page=1&ordering=last_updated

Thank you for your attention!
