### ISSUE TITLE
Prepare data csv

### ISSUE THREAD

**Issue by The-FleetingLove** [unibas-gravis/Occlusion-Robust-MoFA#8]
**What is the format of the content in the dataset csv file? 
Please advise!**

**Comment by ZhenyanSun** [comment]
> **What is the format of the content in the dataset csv file? Please advise!**

Hi I am also interested in this project,the csv format I used like this:
000001.jpg,143.0,189.0,146.0,219.0,150.0,241.0,161.0,256.0,176.0,278.0,191.0,297.0,202.0,312.0,213.0,327.0,239.0,334.0,269.0,323.0,299.0,301.0,321.0,278.0,332.0,252.0,340.0,223.0,340.0,200.0,340.0,174.0,340.0,144.0,135.0,163.0,135.0,159.0,146.0,159.0,154.0,163.0,165.0,167.0,213.0,163.0,224.0,156.0,239.0,152.0,258.0,148.0,277.0,152.0,195.0,196.0,195.0,223.0,191.0,241.0,195.0,252.0,195.0,252.0,198.0,256.0,206.0,260.0,217.0,256.0,224.0,249.0,150.0,185.0,154.0,182.0,165.0,182.0,180.0,189.0,169.0,193.0,157.0,193.0,224.0,185.0,236.0,174.0,247.0,174.0,262.0,178.0,250.0,185.0,236.0,189.0,191.0,271.0,191.0,271.0,202.0,271.0,213.0,271.0,221.0,267.0,243.0,267.0,269.0,263.0,250.0,286.0,236.0,297.0,221.0,301.0,210.0,297.0,198.0,289.0,195.0,271.0,206.0,275.0,217.0,275.0,228.0,275.0,265.0,263.0,232.0,286.0,217.0,289.0,206.0,286.0

**Comment by Yangleyang** [comment]
> > **数据集 csv 文件中内容的格式是什么？请指教！**
> 
> 您好我也对这个项目感兴趣，我使用的 csv 格式是这样的： 000001.jpg,143.0,189.0,146.0,219.0,150.0,241.0,161.0,256.0,176.0,278.0,191.0,297.0,202.0,312.0,213.0,327.0,239.0,334.0,391.0,0.32.3 278.0,332.0,252.0,340.0,223.0,340.0,200.0,340.0,174.0,340.0,144.0,135.0,163.0,135.0,159.0,146.0,159.0,154.0,163.0,165.0,167.0,213.0,163.0,224.0,156.0, 239.0,152.0,258.0,148.0,277.0,152.0,195.0,196.0,195.0,223.0,191.0,241.0,195.0,252.0,195.0,252.0,198.0,256.0,206.0,260.0,217.0,256.0,224.0,249.0,150.0, 185.0,154.0,182.0,165.0,182.0,180.0,189.0,169.0,193.0,193.0,157.0,193.0,193.0,224.0,185.0,185.0,236.0,174.0,174.0,247.0,174.0,174.0,174.0,1178.0,11789.17888.0.88889.8888.0.88888888888.ch。 191.0,271.0,0,202.0,271.0,213.0,271.0,221.0,221.0,267.0,243.0,243.0,267.0,269.0,269.0,269.0,263.0,2550.0,250.0,286.0,236.0,236.0,297.0,2297.0,221.0,221.0,221.0,221.0.bes221.0,20.0,20.0.bes221.0,20.0.9.ct。 275.0,217.0,275.0,228.0,275.0,265.0,263.0,232.0,286.0,217.0,289.0,206.0,286.0

Hello
Can you share your code to save the keypoint data as a csv file?

**Comment by ZhenyanSun** [comment]
for one image you can handle like this, if get landmark from face_alignment
import os
os.environ["CUDA_VISIBLE_DEVICES"]="2,4"
import face_alignment
import csv
from skimage import io

filepath = 'images/img_celeba/'

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,face_detector='sfd')
filename = '1.jpg'
input_img = io.imread(filename)
det = fa.get_landmarks_from_image(input_img)
with open('landmark.csv',encoding='utf-8', mode='a+', newline='') as f:
    writer = csv.writer(f)
    if det is None:
        with open('noFace.csv',encoding='utf-8',mode ='a+',newline='') as m:
            writerm = csv.writer(m)
            filet = []
            filet.append(filename)
            writerm.writerow(filet)
    else:
        landmark = det[0].reshape(136).tolist()
        landmark.insert(0,filename)
        writer.writerow(landmark)

**Comment by ZhenyanSun** [comment]
> 中内容的格式是什么

they are 68 2D landamrks： x0，y0，x1，y1,... x67,y67

**Comment by Yangleyang** [comment]
> > 中内容的格式是什么
> 
> they are 68 2D landamrks： x0，y0，x1，y1,... x67,y67

Thanks a lot, I got it

**Comment by adevra** [comment]
> 

Thanks for posting this,
Corrected indents and changed device to CPU for anyone using it,

`import os
os.environ["CUDA_VISIBLE_DEVICES"]="2,4"
import face_alignment
import csv
from skimage import io

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,face_detector='sfd', device='cpu')
filename = 'yourfile.jpg'
input_img = io.imread('/yourfile.jpg')
det = fa.get_landmarks_from_image(input_img)

with open('landmark.csv',encoding='utf-8', mode='a+', newline='') as f:
        writer = csv.writer(f)
    
        if det is None:
                with open('noFace.csv',encoding='utf-8',mode ='a+',newline='') as m:
                    writerm = csv.writer(m)
                    filet = []
                    filet.append(filename)
                    writerm.writerow(filet)
                
        else:
                landmark = det[0].reshape(136).tolist()
                landmark.insert(0,filename)
                writer.writerow(landmark)`

**Comment by adevra** [comment]
> for one image you can handle like this, if get landmark from face_alignment, if you 批量处理 可以看下 face_alignment 下 get_landmarks_from_directory
> 
> import os os.environ["CUDA_VISIBLE_DEVICES"]="2,4" import face_alignment import csv from skimage import io
> 
> fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,face_detector='sfd') filename = '1.jpg' input_img = io.imread(filename) det = fa.get_landmarks_from_image(input_img) with open('landmark.csv',encoding='utf-8', mode='a+', newline='') as f: writer = csv.writer(f) if det is None: with open('noFace.csv',encoding='utf-8',mode ='a+',newline='') as m: writerm = csv.writer(m) filet = [] filet.append(filename) writerm.writerow(filet) else: landmark = det[0].reshape(136).tolist() landmark.insert(0,filename) writer.writerow(landmark)

@ZhenyanSun  I can't make it run on a folder, maybe a io.imread_collection on line 8 but can't figure it out, can you help?

**Comment by ZhenyanSun** [comment]
> > for one image you can handle like this, if get landmark from face_alignment, if you 批量处理 可以看下 face_alignment 下 get_landmarks_from_directory
> > import os os.environ["CUDA_VISIBLE_DEVICES"]="2,4" import face_alignment import csv from skimage import io
> > fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,face_detector='sfd') filename = '1.jpg' input_img = io.imread(filename) det = fa.get_landmarks_from_image(input_img) with open('landmark.csv',encoding='utf-8', mode='a+', newline='') as f: writer = csv.writer(f) if det is None: with open('noFace.csv',encoding='utf-8',mode ='a+',newline='') as m: writerm = csv.writer(m) filet = [] filet.append(filename) writerm.writerow(filet) else: landmark = det[0].reshape(136).tolist() landmark.insert(0,filename) writer.writerow(landmark)
> 
> @ZhenyanSun I can't make it run on a folder, maybe a io.imread_collection on line 8 but can't figure it out, can you help?

Hi, I can not fully understand your question, can you explain it?
If you mean to batch process image folders, you can use fa.get_landmarks_from_directory as below.
<pre><code>
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,face_detector='sfd',flip_input=False)
filepath = 'images/lfw/'
files = os.listdir(filepath)
for file in files:
    filepathS = filepath + file
    preds = fa.get_landmarks_from_directory(filepathS)
    for item in preds.items():
        print("******************")
        filename = item[0]
        if item[1][0] is None:
            with open('landmarkF/noFace_lfw.csv',encoding='utf-8',mode ='a+',newline='') as m:
                writerm = csv.writer(m)
                writerm.writerow(filename)
        else:
            with open('landmarkF/all_landmarks_lfw.csv',encoding='utf-8', mode='a+', newline='') as f: 
                writer = csv.writer(f)
                landmark = item[1][0].reshape(136).tolist()
                landmark.insert(0,filename)
                writer.writerow(landmark)
</pre></code>

**Comment by adevra** [comment]
Hey, it looked like it's working but no .csv files were written, 
```
(facealign) adunix@DESKTOP-JH0UJT1:~/Occlusion-Robust-MoFA$ /home/adunix/anaconda3/envs/facealign/bin/python /home/adunix/Occlusion-Robust-MoFA/landmarks_folder.py
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
```
I tried to remove filepathS = filepath **+ file**  and it started to process the folder but started appending first 3 images in a loop forever :)


Github Copilot suggested this change in the code and it works now
Thanks for the help again @ZhenyanSun 

```
import os
os.environ["CUDA_VISIBLE_DEVICES"]="2,4"
import face_alignment
import csv
from skimage import io

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,face_detector='sfd',flip_input=False,device='cpu') 
filepath = ('image_root/Dataset/')
files = os.listdir(filepath)

for file in files:
    filename = file
    input_img = io.imread(filepath+file)
    det = fa.get_landmarks_from_image(input_img)
    with open('landmark.csv',encoding='utf-8', mode='a+', newline='') as f:
        writer = csv.writer(f)
        if det is None:
            with open('noFace.csv',encoding='utf-8',mode ='a+',newline='') as m:
                writerm = csv.writer(m)
                filet = []
                filet.append(filename)
                writerm.writerow(filet)
        else:
            landmark = det[0].reshape(136).tolist()
            landmark.insert(0,filename)
            writer.writerow(landmark) 
```

**Comment by ChunLLee** [comment]
Hi, the data pre-processing codes are now available in our docker version. Check the following links to see the details:

https://hub.docker.com/repository/docker/chunluli/focus/tags?page=1&ordering=last_updated

Thank you for your attention!
