### ISSUE TITLE
Pre-trained model?

### ISSUE THREAD

**Issue by HOMGH** [unibas-gravis/Occlusion-Robust-MoFA#9]
Hi,
Thanks for sharing your source code. Is the pre-trained model available or we need to train the model to get it?
Thanks.

**Comment by ChunLLee** [comment]
Hi the pretrained models are now made public in our docker version. Check the following links to see how to use it:

https://github.com/unibas-gravis/Occlusion-Robust-MoFA/blob/main/README.md#docker-image

https://hub.docker.com/repository/docker/chunluli/focus/tags?page=1&ordering=last_updated

Thank you for your attention!
